loglevel: info
cpus: 1
monitoring:
  port: 5555
protocols:
  http:
    enable: true
    mocks_dir: './'
    port: 8080

injection:
  enable: true
origins:
  - http://localhost:3000
validation:
  enable: false
